title: Potential Raspberry Robin Registry Set Internet Settings Zonemap
id: 16a4c7b3-4681-49d0-8d58-3e9b796dcb43
status: experimental
description: |
    Detecting registry modifications related to the proxy configuration of the system, potentially associated with the Raspberry Robin malware, as seen in campaigns running in Q1 2024.
    Raspberry Robin may alter proxy settings to circumvent security measures, ensuring unhindered connection with Command and Control servers for maintaining control over compromised systems if there are any proxy settings that are blocking connections.
references:
    - https://tria.ge/240225-jlylpafb24/behavioral1/analog?main_event=Registry&op=SetValueKeyInt
    - https://tria.ge/240307-1hlldsfe7t/behavioral2/analog?main_event=Registry&op=SetValueKeyInt
    - https://bazaar.abuse.ch/browse/signature/RaspberryRobin/
author: Swachchhanda Shrawan Poudel
date: 2024/03/11
tags:
    - detection.emerging_threats
    - attack.t1112
    - attack.defense_evasion
logsource:
    category: registry_set
    product: windows
    definition: 'Requirements: The registry key "\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\" and its subkey must be monitored'
detection:
    selection_suspicious_image:
        - Image|contains:
              - '\AppData\Local\Temp\'
              - '\Downloads\'
              - '\Windows\Temp\'
              - '\Users\Public\'
        - Image|endswith: '\control.exe'
    selection_suspicious_registry_object:
        TargetObject|contains: '\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\'
    selection_registry_enable:
        TargetObject|endswith:
            - 'ProxyBypass'
            - 'IntranetName'
            - 'UNCAsIntranet'
        Details|contains: 'DWORD (0x00000001)'
    selection_registry_disable:
        TargetObject|endswith: 'AutoDetect'
        Details|contains: 'DWORD (0x00000000)'
    condition: (all of selection_suspicious_*) and (1 of selection_registry_*)
falsepositives:
    - Unknown
# Note: can be upgraded to medium after an initial baseline
level: low
